spring:
  application:
    name: spring-batch-demo

  # ===========================
  # Database Configuration
  # ===========================
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;MODE=MySQL
    username: sa
    password:
  # ===========================
  # H2 Console Configuration
  # ===========================
  h2:
    console:
      enabled: true
      path: /h2-console
  # ===========================
  # JPA / Hibernate Configuration
  # ===========================
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

# ===========================
# Logging
# ===========================

logging:
  level:
    org.springframework.batch: error